openapi: 3.1.0
info:
  version: 1.0.0
  title: tmanoob-api code
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: the api what i created
tags:
  - name: Contacts
    description: operations about contacts
  - name: Auth
    description: operation about auth
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-ndlc.onrender.com
paths:
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/resetPwd.yaml'

  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/sendResetEmail.yaml'

  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'

  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'

  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'

  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'

  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'

  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/contactId/get.yaml'
    delete:
      $ref: '../swagger/paths/contacts/contactId/delete.yaml'
    patch:
      $ref: '../swagger/paths/contacts/contactId/patch.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
